// Code generated by goctl. DO NOT EDIT.
// Source: crosschain.proto

package server

import (
	"context"

	"github.com/jackz-jones/cross-chain-service/internal/logic"
	"github.com/jackz-jones/cross-chain-service/internal/svc"
	"github.com/jackz-jones/cross-chain-service/pb"
)

type CrossChainServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCrossChainServer
}

func NewCrossChainServer(svcCtx *svc.ServiceContext) *CrossChainServer {
	return &CrossChainServer{
		svcCtx: svcCtx,
	}
}

// GetLatestSubscribeHeight 获取最新订阅高度
func (s *CrossChainServer) GetLatestSubscribeHeight(ctx context.Context, in *__.GetLatestSubscribeHeightRequest) (*__.GetLatestSubscribeHeightResponse, error) {
	l := logic.NewGetLatestSubscribeHeightLogic(ctx, s.svcCtx)
	return l.GetLatestSubscribeHeight(in)
}
