// Code generated by goctl. DO NOT EDIT.
// Source: crosschain.proto

package crosschain

import (
	"context"

	"github.com/jackz-jones/cross-chain-service/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLatestSubscribeHeightRequest  = __.GetLatestSubscribeHeightRequest
	GetLatestSubscribeHeightResponse = __.GetLatestSubscribeHeightResponse
	SubscribeHeight                  = __.SubscribeHeight

	CrossChain interface {
		// GetLatestSubscribeHeight 获取最新订阅高度
		GetLatestSubscribeHeight(ctx context.Context, in *GetLatestSubscribeHeightRequest, opts ...grpc.CallOption) (*GetLatestSubscribeHeightResponse, error)
	}

	defaultCrossChain struct {
		cli zrpc.Client
	}
)

func NewCrossChain(cli zrpc.Client) CrossChain {
	return &defaultCrossChain{
		cli: cli,
	}
}

// GetLatestSubscribeHeight 获取最新订阅高度
func (m *defaultCrossChain) GetLatestSubscribeHeight(ctx context.Context, in *GetLatestSubscribeHeightRequest, opts ...grpc.CallOption) (*GetLatestSubscribeHeightResponse, error) {
	client := __.NewCrossChainClient(m.cli.Conn())
	return client.GetLatestSubscribeHeight(ctx, in, opts...)
}
