[ req ]
default_bits = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext

[ req_distinguished_name ]
countryName = Country Name (2 letter code)
countryName_default = CN
stateOrProvinceName = State or Province Name (2 letter code)
stateOrProvinceName_default = SH
localityName = Locality Name (eg, city)
localityName_default = SH
organizationName = Organization Name (eg, company)
organizationName_default = cloudchain
commonName = Common Name (e.g. server FQDN or YOUR name)
commonName_max = 64
commonName_default = cross-chain-service

[ req_ext ]
subjectAltName = @alt_names

[alt_names]

# 证书中可以设置多个 DNS，客户端连接需要知道这个，它要与实际连接的 address host 保持一致
# localhost 一般用于本地 client 连接测试，实际部署去掉即可
DNS.1 = localhost
IP = 127.0.0.1

# DNS.2 = cross-chain-service.cloudchain.com
 