// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: proto/crosschain.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CrossChain_GetLatestSubscribeHeight_FullMethodName = "/proto.CrossChain/GetLatestSubscribeHeight"
)

// CrossChainClient is the client API for CrossChain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrossChainClient interface {
	// GetLatestSubscribeHeight 获取最新订阅高度
	GetLatestSubscribeHeight(ctx context.Context, in *GetLatestSubscribeHeightRequest, opts ...grpc.CallOption) (*GetLatestSubscribeHeightResponse, error)
}

type crossChainClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossChainClient(cc grpc.ClientConnInterface) CrossChainClient {
	return &crossChainClient{cc}
}

func (c *crossChainClient) GetLatestSubscribeHeight(ctx context.Context, in *GetLatestSubscribeHeightRequest, opts ...grpc.CallOption) (*GetLatestSubscribeHeightResponse, error) {
	out := new(GetLatestSubscribeHeightResponse)
	err := c.cc.Invoke(ctx, CrossChain_GetLatestSubscribeHeight_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossChainServer is the server API for CrossChain service.
// All implementations must embed UnimplementedCrossChainServer
// for forward compatibility
type CrossChainServer interface {
	// GetLatestSubscribeHeight 获取最新订阅高度
	GetLatestSubscribeHeight(context.Context, *GetLatestSubscribeHeightRequest) (*GetLatestSubscribeHeightResponse, error)
	mustEmbedUnimplementedCrossChainServer()
}

// UnimplementedCrossChainServer must be embedded to have forward compatible implementations.
type UnimplementedCrossChainServer struct {
}

func (UnimplementedCrossChainServer) GetLatestSubscribeHeight(context.Context, *GetLatestSubscribeHeightRequest) (*GetLatestSubscribeHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestSubscribeHeight not implemented")
}
func (UnimplementedCrossChainServer) mustEmbedUnimplementedCrossChainServer() {}

// UnsafeCrossChainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossChainServer will
// result in compilation errors.
type UnsafeCrossChainServer interface {
	mustEmbedUnimplementedCrossChainServer()
}

func RegisterCrossChainServer(s grpc.ServiceRegistrar, srv CrossChainServer) {
	s.RegisterService(&CrossChain_ServiceDesc, srv)
}

func _CrossChain_GetLatestSubscribeHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSubscribeHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossChainServer).GetLatestSubscribeHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossChain_GetLatestSubscribeHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossChainServer).GetLatestSubscribeHeight(ctx, req.(*GetLatestSubscribeHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossChain_ServiceDesc is the grpc.ServiceDesc for CrossChain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossChain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CrossChain",
	HandlerType: (*CrossChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSubscribeHeight",
			Handler:    _CrossChain_GetLatestSubscribeHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crosschain.proto",
}
