// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: proto/crosschain.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestSubscribeHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`       // 请求id，日志追踪
	ChainName    string `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`       // 哪条链
	ContractName string `protobuf:"bytes,3,opt,name=contractName,proto3" json:"contractName,omitempty"` // 哪个合约
	ChainType    string `protobuf:"bytes,4,opt,name=chainType,proto3" json:"chainType,omitempty"`       // 链类型
	ContractType string `protobuf:"bytes,5,opt,name=contractType,proto3" json:"contractType,omitempty"` // 合约类型
}

func (x *GetLatestSubscribeHeightRequest) Reset() {
	*x = GetLatestSubscribeHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_crosschain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestSubscribeHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSubscribeHeightRequest) ProtoMessage() {}

func (x *GetLatestSubscribeHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosschain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSubscribeHeightRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSubscribeHeightRequest) Descriptor() ([]byte, []int) {
	return file_proto_crosschain_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestSubscribeHeightRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetLatestSubscribeHeightRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *GetLatestSubscribeHeightRequest) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *GetLatestSubscribeHeightRequest) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *GetLatestSubscribeHeightRequest) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

type SubscribeHeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height       uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"` // 高度
	ChainName    string `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`
	ContractName string `protobuf:"bytes,3,opt,name=contractName,proto3" json:"contractName,omitempty"`
	ChainType    string `protobuf:"bytes,4,opt,name=chainType,proto3" json:"chainType,omitempty"`
	ContractType string `protobuf:"bytes,5,opt,name=contractType,proto3" json:"contractType,omitempty"`
}

func (x *SubscribeHeight) Reset() {
	*x = SubscribeHeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_crosschain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeHeight) ProtoMessage() {}

func (x *SubscribeHeight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosschain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeHeight.ProtoReflect.Descriptor instead.
func (*SubscribeHeight) Descriptor() ([]byte, []int) {
	return file_proto_crosschain_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeHeight) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SubscribeHeight) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *SubscribeHeight) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *SubscribeHeight) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *SubscribeHeight) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

type GetLatestSubscribeHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码
	Msg  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 错误信息
	Data *SubscribeHeight `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`  // 结果
}

func (x *GetLatestSubscribeHeightResponse) Reset() {
	*x = GetLatestSubscribeHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_crosschain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestSubscribeHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSubscribeHeightResponse) ProtoMessage() {}

func (x *GetLatestSubscribeHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crosschain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSubscribeHeightResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSubscribeHeightResponse) Descriptor() ([]byte, []int) {
	return file_proto_crosschain_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestSubscribeHeightResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetLatestSubscribeHeightResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetLatestSubscribeHeightResponse) GetData() *SubscribeHeight {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_crosschain_proto protoreflect.FileDescriptor

var file_proto_crosschain_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc3, 0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x74, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x7b, 0x0a, 0x0a, 0x43,
	0x72, 0x6f, 0x73, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x6d, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_crosschain_proto_rawDescOnce sync.Once
	file_proto_crosschain_proto_rawDescData = file_proto_crosschain_proto_rawDesc
)

func file_proto_crosschain_proto_rawDescGZIP() []byte {
	file_proto_crosschain_proto_rawDescOnce.Do(func() {
		file_proto_crosschain_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_crosschain_proto_rawDescData)
	})
	return file_proto_crosschain_proto_rawDescData
}

var file_proto_crosschain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_crosschain_proto_goTypes = []interface{}{
	(*GetLatestSubscribeHeightRequest)(nil),  // 0: proto.GetLatestSubscribeHeightRequest
	(*SubscribeHeight)(nil),                  // 1: proto.SubscribeHeight
	(*GetLatestSubscribeHeightResponse)(nil), // 2: proto.GetLatestSubscribeHeightResponse
}
var file_proto_crosschain_proto_depIdxs = []int32{
	1, // 0: proto.GetLatestSubscribeHeightResponse.data:type_name -> proto.SubscribeHeight
	0, // 1: proto.CrossChain.GetLatestSubscribeHeight:input_type -> proto.GetLatestSubscribeHeightRequest
	2, // 2: proto.CrossChain.GetLatestSubscribeHeight:output_type -> proto.GetLatestSubscribeHeightResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_crosschain_proto_init() }
func file_proto_crosschain_proto_init() {
	if File_proto_crosschain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_crosschain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestSubscribeHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_crosschain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeHeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_crosschain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestSubscribeHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_crosschain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crosschain_proto_goTypes,
		DependencyIndexes: file_proto_crosschain_proto_depIdxs,
		MessageInfos:      file_proto_crosschain_proto_msgTypes,
	}.Build()
	File_proto_crosschain_proto = out.File
	file_proto_crosschain_proto_rawDesc = nil
	file_proto_crosschain_proto_goTypes = nil
	file_proto_crosschain_proto_depIdxs = nil
}
